---
roles:
  - src: git@github.com:ggiinnoo/ansible-role-nginx.git
    scm: git
    version: 1.1.3
    name: ggiinnoo.nginx

  - src: git@github.com:ggiinnoo/ansible-role-vhost.git
    scm: git
    version: 1.0.9
    name: ggiinnoo.vhost